// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiGigsByIdData, DeleteApiGigsByIdResponses, GetApiGigsByIdData, GetApiGigsByIdResponses, GetApiGigsData, GetApiGigsResponses, PostApiGigsData, PostApiGigsResponses, PutApiGigsByIdData, PutApiGigsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiGigs = <ThrowOnError extends boolean = false>(options?: Options<GetApiGigsData, ThrowOnError>) => (options?.client ?? client).get<GetApiGigsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs',
    ...options
});

export const postApiGigs = <ThrowOnError extends boolean = false>(options?: Options<PostApiGigsData, ThrowOnError>) => (options?.client ?? client).post<PostApiGigsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiGigsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGigsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGigsByIdResponses, unknown, ThrowOnError>({ url: '/api/gigs/{id}', ...options });

export const getApiGigsById = <ThrowOnError extends boolean = false>(options: Options<GetApiGigsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiGigsByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}',
    ...options
});

export const putApiGigsById = <ThrowOnError extends boolean = false>(options: Options<PutApiGigsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiGigsByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
