// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiGigsByIdData, DeleteApiGigsByIdResponses, GetApiDashboardStatsTotalGigsData, GetApiDashboardStatsTotalGigsResponses, GetApiGigsByIdData, GetApiGigsByIdResponses, GetApiGigsData, GetApiGigsResponses, GetApiV1ArtistsData, GetApiV1ArtistsResponses, GetApiV1VenuesData, GetApiV1VenuesResponses, PostApiGigsByIdEnrichData, PostApiGigsByIdEnrichResponses, PostApiGigsData, PostApiGigsResponses, PostApiImportCsvData, PostApiImportCsvResponses, PostApiV1ArtistsByIdEnrichData, PostApiV1ArtistsByIdEnrichResponses, PostApiV1VenuesByIdEnrichData, PostApiV1VenuesByIdEnrichResponses, PutApiGigsByIdData, PutApiGigsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiV1Artists = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1ArtistsData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1ArtistsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/artists',
    ...options
});

export const postApiV1ArtistsByIdEnrich = <ThrowOnError extends boolean = false>(options: Options<PostApiV1ArtistsByIdEnrichData, ThrowOnError>) => (options.client ?? client).post<PostApiV1ArtistsByIdEnrichResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/artists/{id}/enrich',
    ...options
});

export const getApiDashboardStatsTotalGigs = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardStatsTotalGigsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardStatsTotalGigsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/stats/total-gigs',
    ...options
});

export const getApiGigs = <ThrowOnError extends boolean = false>(options?: Options<GetApiGigsData, ThrowOnError>) => (options?.client ?? client).get<GetApiGigsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs',
    ...options
});

export const postApiGigs = <ThrowOnError extends boolean = false>(options?: Options<PostApiGigsData, ThrowOnError>) => (options?.client ?? client).post<PostApiGigsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiGigsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGigsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGigsByIdResponses, unknown, ThrowOnError>({ url: '/api/gigs/{id}', ...options });

export const getApiGigsById = <ThrowOnError extends boolean = false>(options: Options<GetApiGigsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiGigsByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}',
    ...options
});

export const putApiGigsById = <ThrowOnError extends boolean = false>(options: Options<PutApiGigsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiGigsByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiGigsByIdEnrich = <ThrowOnError extends boolean = false>(options: Options<PostApiGigsByIdEnrichData, ThrowOnError>) => (options.client ?? client).post<PostApiGigsByIdEnrichResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}/enrich',
    ...options
});

export const postApiImportCsv = <ThrowOnError extends boolean = false>(options?: Options<PostApiImportCsvData, ThrowOnError>) => (options?.client ?? client).post<PostApiImportCsvResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/import/csv',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const getApiV1Venues = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1VenuesData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1VenuesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/venues',
    ...options
});

export const postApiV1VenuesByIdEnrich = <ThrowOnError extends boolean = false>(options: Options<PostApiV1VenuesByIdEnrichData, ThrowOnError>) => (options.client ?? client).post<PostApiV1VenuesByIdEnrichResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/venues/{id}/enrich',
    ...options
});
