// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiGigsByIdData, DeleteApiGigsByIdResponses, GetApiCalendardebugDebugData, GetApiCalendardebugDebugResponses, GetApiCalendarEventsData, GetApiCalendarEventsResponses, GetApiDashboardArtistInsightsData, GetApiDashboardArtistInsightsResponses, GetApiDashboardAverageTicketPriceByYearData, GetApiDashboardAverageTicketPriceByYearResponses, GetApiDashboardGigsPerMonthData, GetApiDashboardGigsPerMonthResponses, GetApiDashboardGigsPerYearData, GetApiDashboardGigsPerYearResponses, GetApiDashboardInterestingInsightsData, GetApiDashboardInterestingInsightsResponses, GetApiDashboardMostHeardSongsData, GetApiDashboardMostHeardSongsResponses, GetApiDashboardStatsData, GetApiDashboardStatsResponses, GetApiDashboardTemporalStatsData, GetApiDashboardTemporalStatsResponses, GetApiDashboardTopArtistsData, GetApiDashboardTopArtistsResponses, GetApiDashboardTopCitiesData, GetApiDashboardTopCitiesResponses, GetApiDashboardTopVenuesData, GetApiDashboardTopVenuesResponses, GetApiDashboardVenueInsightsData, GetApiDashboardVenueInsightsResponses, GetApiGigsByIdData, GetApiGigsByIdResponses, GetApiGigsData, GetApiGigsResponses, GetApiV1ArtistsData, GetApiV1ArtistsResponses, GetApiV1VenuesData, GetApiV1VenuesResponses, GetMediaUploadsByFileNameData, GetMediaUploadsByFileNameResponses, PostApiCalendarImportData, PostApiCalendarImportResponses, PostApiGigsByIdEnrichData, PostApiGigsByIdEnrichResponses, PostApiGigsData, PostApiGigsEnrichAllData, PostApiGigsEnrichAllResponses, PostApiGigsResponses, PostApiImportCsvData, PostApiImportCsvResponses, PostApiV1ArtistsByIdEnrichData, PostApiV1ArtistsByIdEnrichResponses, PostApiV1ArtistsEnrichAllData, PostApiV1ArtistsEnrichAllResponses, PostApiV1VenuesByIdEnrichData, PostApiV1VenuesByIdEnrichResponses, PostApiV1VenuesEnrichAllData, PostApiV1VenuesEnrichAllResponses, PostMediaOptimiseAllData, PostMediaOptimiseAllResponses, PutApiGigsByIdData, PutApiGigsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiV1Artists = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1ArtistsData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1ArtistsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/artists',
    ...options
});

export const postApiV1ArtistsByIdEnrich = <ThrowOnError extends boolean = false>(options: Options<PostApiV1ArtistsByIdEnrichData, ThrowOnError>) => (options.client ?? client).post<PostApiV1ArtistsByIdEnrichResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/artists/{id}/enrich',
    ...options
});

export const postApiV1ArtistsEnrichAll = <ThrowOnError extends boolean = false>(options?: Options<PostApiV1ArtistsEnrichAllData, ThrowOnError>) => (options?.client ?? client).post<PostApiV1ArtistsEnrichAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/artists/enrich-all',
    ...options
});

export const postApiCalendarImport = <ThrowOnError extends boolean = false>(options?: Options<PostApiCalendarImportData, ThrowOnError>) => (options?.client ?? client).post<PostApiCalendarImportResponses, unknown, ThrowOnError>({
    url: '/api/calendar/import',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getApiCalendarEvents = <ThrowOnError extends boolean = false>(options?: Options<GetApiCalendarEventsData, ThrowOnError>) => (options?.client ?? client).get<GetApiCalendarEventsResponses, unknown, ThrowOnError>({ url: '/api/calendar/events', ...options });

export const getApiCalendardebugDebug = <ThrowOnError extends boolean = false>(options?: Options<GetApiCalendardebugDebugData, ThrowOnError>) => (options?.client ?? client).get<GetApiCalendardebugDebugResponses, unknown, ThrowOnError>({ url: '/api/calendardebug/debug', ...options });

export const getApiDashboardStats = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardStatsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardStatsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/stats',
    ...options
});

export const getApiDashboardAverageTicketPriceByYear = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardAverageTicketPriceByYearData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardAverageTicketPriceByYearResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/average-ticket-price-by-year',
    ...options
});

export const getApiDashboardGigsPerYear = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardGigsPerYearData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardGigsPerYearResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/gigs-per-year',
    ...options
});

export const getApiDashboardGigsPerMonth = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardGigsPerMonthData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardGigsPerMonthResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/gigs-per-month',
    ...options
});

export const getApiDashboardTemporalStats = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardTemporalStatsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardTemporalStatsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/temporal-stats',
    ...options
});

export const getApiDashboardArtistInsights = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardArtistInsightsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardArtistInsightsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/artist-insights',
    ...options
});

export const getApiDashboardTopArtists = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardTopArtistsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardTopArtistsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/top-artists',
    ...options
});

export const getApiDashboardVenueInsights = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardVenueInsightsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardVenueInsightsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/venue-insights',
    ...options
});

export const getApiDashboardTopVenues = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardTopVenuesData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardTopVenuesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/top-venues',
    ...options
});

export const getApiDashboardTopCities = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardTopCitiesData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardTopCitiesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/top-cities',
    ...options
});

export const getApiDashboardInterestingInsights = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardInterestingInsightsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardInterestingInsightsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/interesting-insights',
    ...options
});

export const getApiDashboardMostHeardSongs = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardMostHeardSongsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDashboardMostHeardSongsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dashboard/most-heard-songs',
    ...options
});

export const getApiGigs = <ThrowOnError extends boolean = false>(options?: Options<GetApiGigsData, ThrowOnError>) => (options?.client ?? client).get<GetApiGigsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs',
    ...options
});

export const postApiGigs = <ThrowOnError extends boolean = false>(options?: Options<PostApiGigsData, ThrowOnError>) => (options?.client ?? client).post<PostApiGigsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiGigsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGigsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGigsByIdResponses, unknown, ThrowOnError>({ url: '/api/gigs/{id}', ...options });

export const getApiGigsById = <ThrowOnError extends boolean = false>(options: Options<GetApiGigsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiGigsByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}',
    ...options
});

export const putApiGigsById = <ThrowOnError extends boolean = false>(options: Options<PutApiGigsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiGigsByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiGigsByIdEnrich = <ThrowOnError extends boolean = false>(options: Options<PostApiGigsByIdEnrichData, ThrowOnError>) => (options.client ?? client).post<PostApiGigsByIdEnrichResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/{id}/enrich',
    ...options
});

export const postApiGigsEnrichAll = <ThrowOnError extends boolean = false>(options?: Options<PostApiGigsEnrichAllData, ThrowOnError>) => (options?.client ?? client).post<PostApiGigsEnrichAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/gigs/enrich-all',
    ...options
});

export const postApiImportCsv = <ThrowOnError extends boolean = false>(options?: Options<PostApiImportCsvData, ThrowOnError>) => (options?.client ?? client).post<PostApiImportCsvResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/import/csv',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const getMediaUploadsByFileName = <ThrowOnError extends boolean = false>(options: Options<GetMediaUploadsByFileNameData, ThrowOnError>) => (options.client ?? client).get<GetMediaUploadsByFileNameResponses, unknown, ThrowOnError>({ url: '/media/uploads/{fileName}', ...options });

export const postMediaOptimiseAll = <ThrowOnError extends boolean = false>(options?: Options<PostMediaOptimiseAllData, ThrowOnError>) => (options?.client ?? client).post<PostMediaOptimiseAllResponses, unknown, ThrowOnError>({ url: '/media/optimise-all', ...options });

export const getApiV1Venues = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1VenuesData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1VenuesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/venues',
    ...options
});

export const postApiV1VenuesByIdEnrich = <ThrowOnError extends boolean = false>(options: Options<PostApiV1VenuesByIdEnrichData, ThrowOnError>) => (options.client ?? client).post<PostApiV1VenuesByIdEnrichResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/venues/{id}/enrich',
    ...options
});

export const postApiV1VenuesEnrichAll = <ThrowOnError extends boolean = false>(options?: Options<PostApiV1VenuesEnrichAllData, ThrowOnError>) => (options?.client ?? client).post<PostApiV1VenuesEnrichAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/venues/enrich-all',
    ...options
});
