// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5105' | (string & {});
};

export type ArtistInsightsResponse = {
    totalUniqueArtists?: number;
    totalArtistAppearances?: number;
};

export type AverageTicketPriceByYearResponse = {
    year?: number;
    averagePrice?: number;
};

export type DashboardStatsResponse = {
    totalGigs?: number;
    topArtist?: TopArtistStats;
    topVenue?: TopVenueStats;
    topCity?: TopCityStats;
};

export type GetArtistResponse = {
    id?: string;
    name?: string;
    imageUrl?: string | null;
    slug?: string;
};

export type GetGigArtistResponse = {
    artistId?: string;
    name?: string;
    isHeadliner?: boolean;
    imageUrl?: string | null;
};

export type GetGigResponse = {
    id?: string;
    venueId?: string;
    venueName?: string;
    date?: string;
    ticketCost?: number | null;
    ticketType?: TicketType;
    imageUrl?: string | null;
    slug?: string;
    acts?: Array<GetGigArtistResponse>;
};

export type GetVenueResponse = {
    id?: string;
    name?: string;
    city?: string;
    imageUrl?: string | null;
    slug?: string;
};

export type GigsPerMonthResponse = {
    month?: number;
    monthName?: string;
    gigCount?: number;
};

export type GigsPerYearResponse = {
    year?: number;
    gigCount?: number;
};

export type InterestingInsightsResponse = {
    longestSetlist?: LongestSetlistInfo;
    longestGigStreak?: number | null;
    averageGigsPerYear?: number;
};

export type LongestSetlistInfo = {
    gigId?: string;
    artistName?: string;
    venueName?: string;
    date?: string;
    songCount?: number;
};

export type MostHeardSongResponse = {
    songId?: string;
    songTitle?: string;
    artistName?: string;
    timesHeard?: number;
};

export type TemporalStatsResponse = {
    busiestYear?: number | null;
    busiestYearGigCount?: number | null;
    daysSinceLastGig?: number | null;
};

export enum TicketType {
    STANDING = 'Standing',
    SEATED = 'Seated',
    VIP = 'VIP',
    GUEST_LIST = 'Guest List',
    OTHER = 'Other'
}

export type TopArtistResponse = {
    artistId?: string;
    artistName?: string;
    totalAppearances?: number;
    asHeadliner?: number;
    asSupport?: number;
};

export type TopArtistStats = {
    artistName?: string;
    gigCount?: number;
};

export type TopCityResponse = {
    city?: string;
    gigCount?: number;
    uniqueVenues?: number;
};

export type TopCityStats = {
    cityName?: string;
    gigCount?: number;
};

export type TopVenueResponse = {
    venueId?: string;
    venueName?: string;
    city?: string;
    gigCount?: number;
};

export type TopVenueStats = {
    venueName?: string;
    gigCount?: number;
};

export type UpsertGigRequest = {
    venueId: string;
    date: string;
    ticketCost?: number | null;
    ticketType: TicketType;
    imageUrl?: string | null;
    artistIds?: Array<string>;
};

export type VenueInsightsResponse = {
    totalUniqueVenues?: number;
    totalUniqueCities?: number;
};

export type GetApiV1ArtistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/artists';
};

export type GetApiV1ArtistsResponses = {
    /**
     * OK
     */
    200: Array<GetArtistResponse>;
};

export type GetApiV1ArtistsResponse = GetApiV1ArtistsResponses[keyof GetApiV1ArtistsResponses];

export type PostApiV1ArtistsByIdEnrichData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/artists/{id}/enrich';
};

export type PostApiV1ArtistsByIdEnrichResponses = {
    /**
     * OK
     */
    200: GetArtistResponse;
};

export type PostApiV1ArtistsByIdEnrichResponse = PostApiV1ArtistsByIdEnrichResponses[keyof PostApiV1ArtistsByIdEnrichResponses];

export type GetApiDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/stats';
};

export type GetApiDashboardStatsResponses = {
    /**
     * OK
     */
    200: DashboardStatsResponse;
};

export type GetApiDashboardStatsResponse = GetApiDashboardStatsResponses[keyof GetApiDashboardStatsResponses];

export type GetApiDashboardAverageTicketPriceByYearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/average-ticket-price-by-year';
};

export type GetApiDashboardAverageTicketPriceByYearResponses = {
    /**
     * OK
     */
    200: Array<AverageTicketPriceByYearResponse>;
};

export type GetApiDashboardAverageTicketPriceByYearResponse = GetApiDashboardAverageTicketPriceByYearResponses[keyof GetApiDashboardAverageTicketPriceByYearResponses];

export type GetApiDashboardGigsPerYearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/gigs-per-year';
};

export type GetApiDashboardGigsPerYearResponses = {
    /**
     * OK
     */
    200: Array<GigsPerYearResponse>;
};

export type GetApiDashboardGigsPerYearResponse = GetApiDashboardGigsPerYearResponses[keyof GetApiDashboardGigsPerYearResponses];

export type GetApiDashboardGigsPerMonthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/gigs-per-month';
};

export type GetApiDashboardGigsPerMonthResponses = {
    /**
     * OK
     */
    200: Array<GigsPerMonthResponse>;
};

export type GetApiDashboardGigsPerMonthResponse = GetApiDashboardGigsPerMonthResponses[keyof GetApiDashboardGigsPerMonthResponses];

export type GetApiDashboardTemporalStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/temporal-stats';
};

export type GetApiDashboardTemporalStatsResponses = {
    /**
     * OK
     */
    200: TemporalStatsResponse;
};

export type GetApiDashboardTemporalStatsResponse = GetApiDashboardTemporalStatsResponses[keyof GetApiDashboardTemporalStatsResponses];

export type GetApiDashboardArtistInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/artist-insights';
};

export type GetApiDashboardArtistInsightsResponses = {
    /**
     * OK
     */
    200: ArtistInsightsResponse;
};

export type GetApiDashboardArtistInsightsResponse = GetApiDashboardArtistInsightsResponses[keyof GetApiDashboardArtistInsightsResponses];

export type GetApiDashboardTopArtistsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/top-artists';
};

export type GetApiDashboardTopArtistsResponses = {
    /**
     * OK
     */
    200: Array<TopArtistResponse>;
};

export type GetApiDashboardTopArtistsResponse = GetApiDashboardTopArtistsResponses[keyof GetApiDashboardTopArtistsResponses];

export type GetApiDashboardVenueInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/venue-insights';
};

export type GetApiDashboardVenueInsightsResponses = {
    /**
     * OK
     */
    200: VenueInsightsResponse;
};

export type GetApiDashboardVenueInsightsResponse = GetApiDashboardVenueInsightsResponses[keyof GetApiDashboardVenueInsightsResponses];

export type GetApiDashboardTopVenuesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/top-venues';
};

export type GetApiDashboardTopVenuesResponses = {
    /**
     * OK
     */
    200: Array<TopVenueResponse>;
};

export type GetApiDashboardTopVenuesResponse = GetApiDashboardTopVenuesResponses[keyof GetApiDashboardTopVenuesResponses];

export type GetApiDashboardTopCitiesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/top-cities';
};

export type GetApiDashboardTopCitiesResponses = {
    /**
     * OK
     */
    200: Array<TopCityResponse>;
};

export type GetApiDashboardTopCitiesResponse = GetApiDashboardTopCitiesResponses[keyof GetApiDashboardTopCitiesResponses];

export type GetApiDashboardInterestingInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/interesting-insights';
};

export type GetApiDashboardInterestingInsightsResponses = {
    /**
     * OK
     */
    200: InterestingInsightsResponse;
};

export type GetApiDashboardInterestingInsightsResponse = GetApiDashboardInterestingInsightsResponses[keyof GetApiDashboardInterestingInsightsResponses];

export type GetApiDashboardMostHeardSongsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/most-heard-songs';
};

export type GetApiDashboardMostHeardSongsResponses = {
    /**
     * OK
     */
    200: Array<MostHeardSongResponse>;
};

export type GetApiDashboardMostHeardSongsResponse = GetApiDashboardMostHeardSongsResponses[keyof GetApiDashboardMostHeardSongsResponses];

export type GetApiGigsData = {
    body?: never;
    path?: never;
    query?: {
        VenueId?: string;
        City?: string;
        FromDate?: string;
        ToDate?: string;
        ArtistId?: string;
    };
    url: '/api/gigs';
};

export type GetApiGigsResponses = {
    /**
     * OK
     */
    200: Array<GetGigResponse>;
};

export type GetApiGigsResponse = GetApiGigsResponses[keyof GetApiGigsResponses];

export type PostApiGigsData = {
    body?: UpsertGigRequest;
    path?: never;
    query?: never;
    url: '/api/gigs';
};

export type PostApiGigsResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type PostApiGigsResponse = PostApiGigsResponses[keyof PostApiGigsResponses];

export type DeleteApiGigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}';
};

export type DeleteApiGigsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}';
};

export type GetApiGigsByIdResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type GetApiGigsByIdResponse = GetApiGigsByIdResponses[keyof GetApiGigsByIdResponses];

export type PutApiGigsByIdData = {
    body?: UpsertGigRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}';
};

export type PutApiGigsByIdResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type PutApiGigsByIdResponse = PutApiGigsByIdResponses[keyof PutApiGigsByIdResponses];

export type PostApiGigsByIdEnrichData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}/enrich';
};

export type PostApiGigsByIdEnrichResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type PostApiGigsByIdEnrichResponse = PostApiGigsByIdEnrichResponses[keyof PostApiGigsByIdEnrichResponses];

export type PostApiImportCsvData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/import/csv';
};

export type PostApiImportCsvResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1VenuesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/venues';
};

export type GetApiV1VenuesResponses = {
    /**
     * OK
     */
    200: Array<GetVenueResponse>;
};

export type GetApiV1VenuesResponse = GetApiV1VenuesResponses[keyof GetApiV1VenuesResponses];

export type PostApiV1VenuesByIdEnrichData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/venues/{id}/enrich';
};

export type PostApiV1VenuesByIdEnrichResponses = {
    /**
     * OK
     */
    200: GetVenueResponse;
};

export type PostApiV1VenuesByIdEnrichResponse = PostApiV1VenuesByIdEnrichResponses[keyof PostApiV1VenuesByIdEnrichResponses];
