// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5105' | (string & {});
};

export type ArtistInsightsResponse = {
    totalUniqueArtists?: number;
    totalArtistAppearances?: number;
};

export type AttendeeInsightsResponse = {
    totalUniqueAttendees?: number;
    totalGigsWithAttendees?: number;
};

export type AverageTicketPriceByYearResponse = {
    year?: number;
    averagePrice?: number;
};

export type DashboardStatsResponse = {
    totalGigs?: number;
    topArtist?: TopArtistStats;
    topVenue?: TopVenueStats;
    topCity?: TopCityStats;
    topAttendee?: TopAttendeeStats;
};

export type FestivalGigOrderRequest = {
    gigId?: string;
    order?: number;
};

export type GetArtistResponse = {
    id?: string;
    name?: string;
    imageUrl?: string | null;
    slug?: string;
};

export type GetAttendeeResponse = {
    id?: string;
    name?: string;
    slug?: string;
};

export type GetCalendarEventResponse = {
    id?: string;
    title?: string;
    startDateTime?: string;
    endDateTime?: string | null;
    location?: string | null;
    description?: string | null;
};

export type GetFestivalResponse = {
    id?: string;
    name?: string;
    year?: number | null;
    slug?: string;
    imageUrl?: string | null;
    gigs?: Array<GetGigResponse> | null;
    startDate?: string | null;
    endDate?: string | null;
    price?: number | null;
    dailyPrice?: number | null;
    attendees?: Array<GetPersonResponse>;
};

export type GetGigArtistResponse = {
    artistId?: string;
    name?: string;
    isHeadliner?: boolean;
    imageUrl?: string | null;
    setlist?: Array<string>;
};

export type GetGigAttendeeResponse = {
    personId?: string;
    personName?: string;
};

export type GetGigResponse = {
    id?: string;
    venueId?: string;
    venueName?: string;
    festivalId?: string | null;
    festivalName?: string | null;
    date?: string;
    order?: number;
    ticketCost?: number | null;
    ticketType?: TicketType;
    imageUrl?: string | null;
    slug?: string;
    acts?: Array<GetGigArtistResponse>;
    attendees?: Array<GetGigAttendeeResponse>;
};

export type GetGigResponsePaginatedResponse = {
    items?: Array<GetGigResponse>;
    page?: number;
    pageSize?: number;
    totalCount?: number;
    readonly totalPages?: number;
};

export type GetPersonResponse = {
    id?: string;
    name?: string;
    slug?: string;
};

export type GetVenueResponse = {
    id?: string;
    name?: string;
    city?: string;
    imageUrl?: string | null;
    slug?: string;
};

export type GigArtistRequest = {
    artistId?: string;
    isHeadliner?: boolean;
    order?: number;
    setlistUrl?: string | null;
    setlist?: Array<string>;
};

export type GigsPerMonthResponse = {
    month?: number;
    monthName?: string;
    gigCount?: number;
};

export type GigsPerYearResponse = {
    year?: number;
    gigCount?: number;
};

export type ImportCalendarEventsRequest = {
    startDate?: string | null;
    endDate?: string | null;
};

export type ImportCalendarEventsResponse = {
    eventsFound?: number;
    gigsCreated?: number;
    gigsUpdated?: number;
    eventsSkipped?: number;
    venuesCreated?: number;
    message?: string;
};

export type InterestingInsightsResponse = {
    longestSetlist?: LongestSetlistInfo;
    longestGigStreak?: number | null;
    averageGigsPerYear?: number;
};

export type LongestSetlistInfo = {
    gigId?: string;
    artistName?: string;
    venueName?: string;
    date?: string;
    songCount?: number;
};

export type MostHeardSongResponse = {
    songId?: string;
    songTitle?: string;
    artistName?: string;
    timesHeard?: number;
};

export type TemporalStatsResponse = {
    busiestYear?: number | null;
    busiestYearGigCount?: number | null;
    daysSinceLastGig?: number | null;
};

export enum TicketType {
    STANDING = 'Standing',
    SEATED = 'Seated',
    VIP = 'VIP',
    GUEST_LIST = 'Guest List',
    OTHER = 'Other'
}

export type TopArtistResponse = {
    artistId?: string;
    artistName?: string;
    totalAppearances?: number;
    asHeadliner?: number;
    asSupport?: number;
};

export type TopArtistStats = {
    artistName?: string;
    gigCount?: number;
};

export type TopAttendeeResponse = {
    personId?: string;
    personName?: string;
    gigCount?: number;
};

export type TopAttendeeStats = {
    personName?: string;
    gigCount?: number;
};

export type TopCityResponse = {
    city?: string;
    gigCount?: number;
    uniqueVenues?: number;
};

export type TopCityStats = {
    cityName?: string;
    gigCount?: number;
};

export type TopVenueResponse = {
    venueId?: string;
    venueName?: string;
    city?: string;
    gigCount?: number;
};

export type TopVenueStats = {
    venueName?: string;
    gigCount?: number;
};

export type UpsertFestivalRequest = {
    name: string;
    year?: number | null;
    imageUrl?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    price?: number | null;
    attendees?: Array<string>;
    gigs?: Array<FestivalGigOrderRequest>;
};

export type UpsertGigRequest = {
    venueId?: string | null;
    venueName?: string | null;
    venueCity?: string | null;
    festivalId?: string | null;
    festivalName?: string | null;
    date: string;
    order?: number;
    ticketCost?: number | null;
    ticketType: TicketType;
    imageUrl?: string | null;
    acts?: Array<GigArtistRequest>;
    attendees?: Array<string>;
};

export type UpsertPersonRequest = {
    name: string;
};

export type VenueInsightsResponse = {
    totalUniqueVenues?: number;
    totalUniqueCities?: number;
};

export type GetGigResponsePaginatedResponseWritable = {
    items?: Array<GetGigResponse>;
    page?: number;
    pageSize?: number;
    totalCount?: number;
};

export type GetApiArtistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/artists';
};

export type GetApiArtistsResponses = {
    /**
     * OK
     */
    200: Array<GetArtistResponse>;
};

export type GetApiArtistsResponse = GetApiArtistsResponses[keyof GetApiArtistsResponses];

export type PostApiArtistsByIdEnrichData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/artists/{id}/enrich';
};

export type PostApiArtistsByIdEnrichResponses = {
    /**
     * OK
     */
    200: GetArtistResponse;
};

export type PostApiArtistsByIdEnrichResponse = PostApiArtistsByIdEnrichResponses[keyof PostApiArtistsByIdEnrichResponses];

export type PostApiArtistsEnrichAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/artists/enrich-all';
};

export type PostApiArtistsEnrichAllResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostApiArtistsEnrichAllResponse = PostApiArtistsEnrichAllResponses[keyof PostApiArtistsEnrichAllResponses];

export type GetApiAttendeesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/attendees';
};

export type GetApiAttendeesResponses = {
    /**
     * OK
     */
    200: Array<GetAttendeeResponse>;
};

export type GetApiAttendeesResponse = GetApiAttendeesResponses[keyof GetApiAttendeesResponses];

export type PostApiCalendarImportData = {
    body?: ImportCalendarEventsRequest;
    path?: never;
    query?: never;
    url: '/api/calendar/import';
};

export type PostApiCalendarImportResponses = {
    /**
     * OK
     */
    200: ImportCalendarEventsResponse;
};

export type PostApiCalendarImportResponse = PostApiCalendarImportResponses[keyof PostApiCalendarImportResponses];

export type GetApiCalendarEventsData = {
    body?: never;
    path?: never;
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/calendar/events';
};

export type GetApiCalendarEventsResponses = {
    /**
     * OK
     */
    200: Array<GetCalendarEventResponse>;
};

export type GetApiCalendarEventsResponse = GetApiCalendarEventsResponses[keyof GetApiCalendarEventsResponses];

export type GetApiDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/stats';
};

export type GetApiDashboardStatsResponses = {
    /**
     * OK
     */
    200: DashboardStatsResponse;
};

export type GetApiDashboardStatsResponse = GetApiDashboardStatsResponses[keyof GetApiDashboardStatsResponses];

export type GetApiDashboardAverageTicketPriceByYearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/average-ticket-price-by-year';
};

export type GetApiDashboardAverageTicketPriceByYearResponses = {
    /**
     * OK
     */
    200: Array<AverageTicketPriceByYearResponse>;
};

export type GetApiDashboardAverageTicketPriceByYearResponse = GetApiDashboardAverageTicketPriceByYearResponses[keyof GetApiDashboardAverageTicketPriceByYearResponses];

export type GetApiDashboardGigsPerYearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/gigs-per-year';
};

export type GetApiDashboardGigsPerYearResponses = {
    /**
     * OK
     */
    200: Array<GigsPerYearResponse>;
};

export type GetApiDashboardGigsPerYearResponse = GetApiDashboardGigsPerYearResponses[keyof GetApiDashboardGigsPerYearResponses];

export type GetApiDashboardGigsPerMonthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/gigs-per-month';
};

export type GetApiDashboardGigsPerMonthResponses = {
    /**
     * OK
     */
    200: Array<GigsPerMonthResponse>;
};

export type GetApiDashboardGigsPerMonthResponse = GetApiDashboardGigsPerMonthResponses[keyof GetApiDashboardGigsPerMonthResponses];

export type GetApiDashboardTemporalStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/temporal-stats';
};

export type GetApiDashboardTemporalStatsResponses = {
    /**
     * OK
     */
    200: TemporalStatsResponse;
};

export type GetApiDashboardTemporalStatsResponse = GetApiDashboardTemporalStatsResponses[keyof GetApiDashboardTemporalStatsResponses];

export type GetApiDashboardArtistInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/artist-insights';
};

export type GetApiDashboardArtistInsightsResponses = {
    /**
     * OK
     */
    200: ArtistInsightsResponse;
};

export type GetApiDashboardArtistInsightsResponse = GetApiDashboardArtistInsightsResponses[keyof GetApiDashboardArtistInsightsResponses];

export type GetApiDashboardTopArtistsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/top-artists';
};

export type GetApiDashboardTopArtistsResponses = {
    /**
     * OK
     */
    200: Array<TopArtistResponse>;
};

export type GetApiDashboardTopArtistsResponse = GetApiDashboardTopArtistsResponses[keyof GetApiDashboardTopArtistsResponses];

export type GetApiDashboardVenueInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/venue-insights';
};

export type GetApiDashboardVenueInsightsResponses = {
    /**
     * OK
     */
    200: VenueInsightsResponse;
};

export type GetApiDashboardVenueInsightsResponse = GetApiDashboardVenueInsightsResponses[keyof GetApiDashboardVenueInsightsResponses];

export type GetApiDashboardTopVenuesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/top-venues';
};

export type GetApiDashboardTopVenuesResponses = {
    /**
     * OK
     */
    200: Array<TopVenueResponse>;
};

export type GetApiDashboardTopVenuesResponse = GetApiDashboardTopVenuesResponses[keyof GetApiDashboardTopVenuesResponses];

export type GetApiDashboardTopCitiesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/top-cities';
};

export type GetApiDashboardTopCitiesResponses = {
    /**
     * OK
     */
    200: Array<TopCityResponse>;
};

export type GetApiDashboardTopCitiesResponse = GetApiDashboardTopCitiesResponses[keyof GetApiDashboardTopCitiesResponses];

export type GetApiDashboardInterestingInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/interesting-insights';
};

export type GetApiDashboardInterestingInsightsResponses = {
    /**
     * OK
     */
    200: InterestingInsightsResponse;
};

export type GetApiDashboardInterestingInsightsResponse = GetApiDashboardInterestingInsightsResponses[keyof GetApiDashboardInterestingInsightsResponses];

export type GetApiDashboardMostHeardSongsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/most-heard-songs';
};

export type GetApiDashboardMostHeardSongsResponses = {
    /**
     * OK
     */
    200: Array<MostHeardSongResponse>;
};

export type GetApiDashboardMostHeardSongsResponse = GetApiDashboardMostHeardSongsResponses[keyof GetApiDashboardMostHeardSongsResponses];

export type GetApiDashboardAttendeeInsightsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/attendee-insights';
};

export type GetApiDashboardAttendeeInsightsResponses = {
    /**
     * OK
     */
    200: AttendeeInsightsResponse;
};

export type GetApiDashboardAttendeeInsightsResponse = GetApiDashboardAttendeeInsightsResponses[keyof GetApiDashboardAttendeeInsightsResponses];

export type GetApiDashboardTopAttendeesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/dashboard/top-attendees';
};

export type GetApiDashboardTopAttendeesResponses = {
    /**
     * OK
     */
    200: Array<TopAttendeeResponse>;
};

export type GetApiDashboardTopAttendeesResponse = GetApiDashboardTopAttendeesResponses[keyof GetApiDashboardTopAttendeesResponses];

export type GetApiFestivalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/festivals';
};

export type GetApiFestivalsResponses = {
    /**
     * OK
     */
    200: Array<GetFestivalResponse>;
};

export type GetApiFestivalsResponse = GetApiFestivalsResponses[keyof GetApiFestivalsResponses];

export type PostApiFestivalsData = {
    body?: UpsertFestivalRequest;
    path?: never;
    query?: never;
    url: '/api/festivals';
};

export type PostApiFestivalsResponses = {
    /**
     * OK
     */
    200: GetFestivalResponse;
};

export type PostApiFestivalsResponse = PostApiFestivalsResponses[keyof PostApiFestivalsResponses];

export type DeleteApiFestivalsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/festivals/{id}';
};

export type DeleteApiFestivalsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiFestivalsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/festivals/{id}';
};

export type GetApiFestivalsByIdResponses = {
    /**
     * OK
     */
    200: GetFestivalResponse;
};

export type GetApiFestivalsByIdResponse = GetApiFestivalsByIdResponses[keyof GetApiFestivalsByIdResponses];

export type PutApiFestivalsByIdData = {
    body?: UpsertFestivalRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/festivals/{id}';
};

export type PutApiFestivalsByIdResponses = {
    /**
     * OK
     */
    200: GetFestivalResponse;
};

export type PutApiFestivalsByIdResponse = PutApiFestivalsByIdResponses[keyof PutApiFestivalsByIdResponses];

export type GetApiGigsData = {
    body?: never;
    path?: never;
    query?: {
        VenueId?: string;
        FestivalId?: string;
        City?: string;
        FromDate?: string;
        ToDate?: string;
        ArtistId?: string;
        Search?: string;
        Page?: number;
        PageSize?: number;
        AttendeeId?: string;
    };
    url: '/api/gigs';
};

export type GetApiGigsResponses = {
    /**
     * OK
     */
    200: GetGigResponsePaginatedResponse;
};

export type GetApiGigsResponse = GetApiGigsResponses[keyof GetApiGigsResponses];

export type PostApiGigsData = {
    body?: UpsertGigRequest;
    path?: never;
    query?: never;
    url: '/api/gigs';
};

export type PostApiGigsResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type PostApiGigsResponse = PostApiGigsResponses[keyof PostApiGigsResponses];

export type DeleteApiGigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}';
};

export type DeleteApiGigsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}';
};

export type GetApiGigsByIdResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type GetApiGigsByIdResponse = GetApiGigsByIdResponses[keyof GetApiGigsByIdResponses];

export type PutApiGigsByIdData = {
    body?: UpsertGigRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}';
};

export type PutApiGigsByIdResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type PutApiGigsByIdResponse = PutApiGigsByIdResponses[keyof PutApiGigsByIdResponses];

export type PostApiGigsByIdEnrichData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/gigs/{id}/enrich';
};

export type PostApiGigsByIdEnrichResponses = {
    /**
     * OK
     */
    200: GetGigResponse;
};

export type PostApiGigsByIdEnrichResponse = PostApiGigsByIdEnrichResponses[keyof PostApiGigsByIdEnrichResponses];

export type PostApiGigsEnrichAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gigs/enrich-all';
};

export type PostApiGigsEnrichAllResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostApiGigsEnrichAllResponse = PostApiGigsEnrichAllResponses[keyof PostApiGigsEnrichAllResponses];

export type PostApiImportCsvData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/import/csv';
};

export type PostApiImportCsvResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostApiImportCsvResponse = PostApiImportCsvResponses[keyof PostApiImportCsvResponses];

export type GetMediaUploadsByFileNameData = {
    body?: never;
    path: {
        fileName: string;
    };
    query?: never;
    url: '/media/uploads/{fileName}';
};

export type GetMediaUploadsByFileNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPersonsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/persons';
};

export type GetApiPersonsResponses = {
    /**
     * OK
     */
    200: Array<GetPersonResponse>;
};

export type GetApiPersonsResponse = GetApiPersonsResponses[keyof GetApiPersonsResponses];

export type PostApiPersonsData = {
    body?: UpsertPersonRequest;
    path?: never;
    query?: never;
    url: '/api/persons';
};

export type PostApiPersonsResponses = {
    /**
     * OK
     */
    200: GetPersonResponse;
};

export type PostApiPersonsResponse = PostApiPersonsResponses[keyof PostApiPersonsResponses];

export type DeleteApiPersonsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/persons/{id}';
};

export type DeleteApiPersonsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPersonsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/persons/{id}';
};

export type GetApiPersonsByIdResponses = {
    /**
     * OK
     */
    200: GetPersonResponse;
};

export type GetApiPersonsByIdResponse = GetApiPersonsByIdResponses[keyof GetApiPersonsByIdResponses];

export type PutApiPersonsByIdData = {
    body?: UpsertPersonRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/persons/{id}';
};

export type PutApiPersonsByIdResponses = {
    /**
     * OK
     */
    200: GetPersonResponse;
};

export type PutApiPersonsByIdResponse = PutApiPersonsByIdResponses[keyof PutApiPersonsByIdResponses];

export type GetApiVenuesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/venues';
};

export type GetApiVenuesResponses = {
    /**
     * OK
     */
    200: Array<GetVenueResponse>;
};

export type GetApiVenuesResponse = GetApiVenuesResponses[keyof GetApiVenuesResponses];

export type PostApiVenuesByIdEnrichData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/venues/{id}/enrich';
};

export type PostApiVenuesByIdEnrichResponses = {
    /**
     * OK
     */
    200: GetVenueResponse;
};

export type PostApiVenuesByIdEnrichResponse = PostApiVenuesByIdEnrichResponses[keyof PostApiVenuesByIdEnrichResponses];

export type PostApiVenuesEnrichAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/venues/enrich-all';
};

export type PostApiVenuesEnrichAllResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostApiVenuesEnrichAllResponse = PostApiVenuesEnrichAllResponses[keyof PostApiVenuesEnrichAllResponses];
